[package]
name = "wiki_stats"
version = "1.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0"
zip = "0.6.6"
serde = "1"
serde_derive = "1"
serde_json = "1"
